#!/usr/bin/env python3
"""Regenerate `custom_components/healthbox3/zone_icons.py` from Renson's own
zone pictograms.

Usage:
    python3 scripts/generate_zone_icons.py <dir of ic_zone_*.svg>

The input is the set of `ic_zone_*.svg` files converted from the Renson
Android app's VectorDrawables (`res/drawable/ic_zone_*.xml`). Only the
small variants are read: the `_large` ones are the same drawing at the
same 24x24 viewBox, which is the size Home Assistant's icon renderer
expects, so shipping both would only double the payload.

Each icon becomes a single SVG path string, because that is all Home
Assistant's icon renderer takes. Most are already one path; the two that
cannot be flattened without changing the drawing are dropped (see
`extract`) and their symbols fall back to a neighbouring icon.
"""

from __future__ import annotations

import pathlib
import sys
import xml.etree.ElementTree as ET

SVG_NS = "{http://www.w3.org/2000/svg}"
EXPECTED_VIEW_BOX = "0 0 24 24"

HEADER = '''"""Renson's own zone pictograms, as SVG path data.

GENERATED by scripts/generate_zone_icons.py - do not edit by hand.

Source: the Renson Android app's `res/drawable/ic_zone_*.xml`
VectorDrawables. All are 24x24, which is the viewBox Home Assistant's
icon renderer assumes, so they need no rescaling.

These are used two ways: served to the frontend as a `custom:` icon set
(see icon_set.py), and mapped from each room's reported symbol by
ROOM_SYMBOL_TO_ICON below.
"""

from __future__ import annotations

# Every value the device has been seen to report in a room's `icon`
# parameter, mapped to the pictogram Renson's own app draws for it. The
# 24 keys were read out of the app's native library; several share an
# icon, which is why there are fewer icons than keys (both kitchen
# variants draw the same chef's hat, both laundry variants the same
# machine, and a bathroom with or without a toilet is the same bathtub).
#
# Deliberately NOT a guess-friendly mapping: a value that is not in here
# falls back to FALLBACK_ICON rather than being approximated, because
# showing the wrong room is worse than showing a generic one.
ROOM_SYMBOL_TO_ICON: dict[str, str] = {
    "BabyRoom": "baby",
    "Basement": "basement",
    "BathRoom": "bath",
    "BathRoomWithoutToilet": "bath",
    "BedRoom": "bed",
    "ClosedKitchen": "kitchen",
    # Renson's own cooker-hood drawing is stroke art, which Home Assistant
    # cannot render (it fills icon paths). Falls back to the kitchen hat -
    # a cooker hood is a kitchen extraction point, so the substitution
    # reads correctly even though it is not the original drawing.
    "CookerHood": "kitchen",
    "DiningRoom": "dining",
    "Dresser": "dresser",
    "Garage": "garage",
    "Hallway": "hall",
    "HobbyRoom": "hobby",
    "Kitchen": "kitchen",
    "LaundryRoom": "washing",
    "LivingRoom": "living",
    "MediaRoom": "media",
    "Office": "office",
    "PlayRoom": "play",
    "Shower": "shower",
    "SittingRoom": "sitting",
    "Storage": "storage",
    # Same problem, different cause: the studio drawing is two paths under
    # different fill rules and cannot be flattened into one. A studio flat
    # is drawn by Renson as a bed beside a shower, so the bed is the
    # closest single-concept stand-in.
    "StudioFlat": "bed",
    "Toilet": "toilet",
    "WashingRoom": "washing",
}

# What an unrecognised symbol gets. Renson's own picker shows this house
# for entries it has no specific drawing for, so it is their fallback as
# much as ours.
FALLBACK_ICON = "house"

# The icon set this registers with the frontend. It is also the half of an
# icon name before the colon: `window.customIconsets["healthbox"]` is what
# resolves `healthbox:bath`. Use icon_set.icon_name() to build those names
# rather than formatting them by hand - getting the shape wrong renders
# nothing at all, silently.
#
# Named after the product, not the manufacturer, on purpose.
# `window.customIconsets` is one namespace shared by every integration in
# the frontend, first registration wins, and Home Assistant core already
# ships an integration whose domain is `renson` (the Endura Delta). Taking
# `renson` there would be claiming a name that is not this integration's to
# claim, and a collision shows up as icons that silently stop resolving.
ICON_PREFIX = "healthbox"

'''


def extract(path: pathlib.Path) -> str | None:
    """Return one icon's path data, or None if it can't be represented.

    Home Assistant renders a custom icon as a single *filled* path, so an
    icon survives this only if flattening it changes nothing:

    - stroke-only art (`fill="none"` plus a stroke) would be filled
      instead of outlined, turning a line drawing into a blob;
    - several paths under different fill rules cannot be concatenated
      without changing which regions end up filled.

    Both cases were measured by rasterising the original against the
    flattened candidate; neither was close (27% and 17% of the canvas
    differing). So they are dropped here and their symbols point at a
    neighbouring icon in ROOM_SYMBOL_TO_ICON, which is honest about being
    an approximation rather than shipping a wrong drawing.
    """
    root = ET.parse(path).getroot()
    view_box = root.get("viewBox")
    if view_box != EXPECTED_VIEW_BOX:
        sys.exit(f"{path.name}: viewBox is {view_box!r}, expected {EXPECTED_VIEW_BOX!r}")

    paths = root.findall(f".//{SVG_NS}path")
    if not paths:
        sys.exit(f"{path.name}: no <path>")

    if any(p.get("fill", "").lower() == "none" for p in paths):
        print(f"  skipped {path.name}: stroke-only art", file=sys.stderr)
        return None
    if len({p.get("fill-rule", "nonzero") for p in paths}) > 1:
        print(f"  skipped {path.name}: mixed fill rules", file=sys.stderr)
        return None
    return "".join(p.get("d", "") for p in paths)


def main() -> None:
    """Write the generated module to stdout."""
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = pathlib.Path(sys.argv[1])

    icons: dict[str, str] = {}
    for svg in sorted(source.glob("ic_zone_*.svg")):
        if svg.stem.endswith("_large"):
            continue
        data = extract(svg)
        if data is not None:
            icons[svg.stem.removeprefix("ic_zone_")] = data

    if not icons:
        sys.exit(f"No ic_zone_*.svg found in {source}")

    out = [HEADER, "ZONE_ICON_PATHS: dict[str, str] = {\n"]
    for name, data in sorted(icons.items()):
        out.append(f'    "{name}": (\n        "{data}"\n    ),\n')
    out.append("}\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
