#!/usr/bin/env python3
"""Regenerate `custom_components/healthbox3/scene_assets.py`.

Usage:
    python3 scripts/generate_scene_assets.py <dir of img_*.svg>

The input is the Renson Android app's own drawings of the unit, converted
from `res/drawable/img_healthbox_*.xml` and `img_valve_*.xml`.

Unlike the zone pictograms (see generate_zone_icons.py), these are not
constrained to a single path: the card draws them as ordinary inline SVG,
so each asset is kept as its markup exactly as drawn - strokes, fills,
grouping and all.
"""

from __future__ import annotations

import pathlib
import sys
import xml.etree.ElementTree as ET

SVG_NS = "http://www.w3.org/2000/svg"

# The scene the app itself lays out, read from the decoded
# `view_health_box.xml`: a 540x540 stage with the unit at (195,195) 150
# wide, and the exhaust stub at (278,165) 54x30. Reproduced rather than
# re-derived so the drawing keeps the proportions Renson drew it with.
GEOMETRY = {
    "stage": 540,
    "base_x": 195,
    "base_y": 195,
    "base_size": 150,
    "exhaust_x": 278,
    "exhaust_y": 165,
    "exhaust_w": 54,
    "exhaust_h": 30,
    # A valve seen from the side (left/right edges) and from the end
    # (top/bottom edges); the two drawings are the same art rotated, and
    # keep their own aspect.
    "valve_side_w": 39,
    "valve_side_h": 53,
    "valve_end_w": 53,
    "valve_end_h": 39,
}

WANTED = (
    "img_healthbox_base",
    "img_healthbox_exhaust",
    "img_valve_manual_left",
    "img_valve_manual_top",
    "img_valve_manual_error_left",
    "img_valve_manual_error_top",
    "img_valve_closed_left",
    "img_valve_closed_top",
)

HEADER = '''"""Renson's own drawing of the unit, for the Healthbox card.

GENERATED by scripts/generate_scene_assets.py - do not edit by hand.

Source: the Renson Android app's `res/drawable/img_healthbox_*.xml` and
`img_valve_*.xml` VectorDrawables, plus the stage geometry decoded from
its `view_health_box.xml` layout.

What the three valve drawings mean, read off the art itself: `manual` is
the duct connection (a bracket), `closed` is the blanking cap with its
double shoulder, and the `error` variants are the same connection marked
as faulty. The app's `auto` drawing is just a circle - the badge the
number sits in - which the card draws itself rather than importing, so
the number and its circle stay together.
"""

from __future__ import annotations

'''


def fragment(path: pathlib.Path) -> str:
    """Return an asset's inner markup, ready to drop inside a <g>."""
    root = ET.parse(path).getroot()
    ET.register_namespace("", SVG_NS)
    out = "".join(ET.tostring(child, encoding="unicode") for child in root)
    # ElementTree re-declares the namespace on every serialised subtree;
    # inside a host <svg> it is already in scope and only bloats the file.
    return out.replace(f' xmlns="{SVG_NS}"', "")


def main() -> None:
    """Write the generated module to stdout."""
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = pathlib.Path(sys.argv[1])

    assets: dict[str, str] = {}
    for name in WANTED:
        svg = source / f"{name}.svg"
        if not svg.is_file():
            sys.exit(f"missing {svg}")
        assets[name.removeprefix("img_")] = fragment(svg)

    out = [HEADER, "SCENE_GEOMETRY: dict[str, int] = {\n"]
    for key, value in GEOMETRY.items():
        out.append(f'    "{key}": {value},\n')
    out.append("}\n\nSCENE_ASSETS: dict[str, str] = {\n")
    for name, markup in assets.items():
        out.append(f'    "{name}": (\n        {markup!r}\n    ),\n')
    out.append("}\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
